name: PLASMAG
channels:
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - alabaster=0.7.16=pyhd8ed1ab_0
  - astroid=3.1.0=py39h6e9494a_0
  - babel=2.14.0=pyhd8ed1ab_0
  - brotli=1.1.0=h0dc2134_1
  - brotli-bin=1.1.0=h0dc2134_1
  - brotli-python=1.1.0=py39h840bb9f_1
  - bzip2=1.0.8=h10d778d_5
  - ca-certificates=2024.2.2=h8857fd0_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.0=py39h6be1789_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - docutils=0.20.1=py39h6e9494a_3
  - fonttools=4.50.0=py39ha09f3b3_0
  - freetype=2.12.1=h60636b9_2
  - idna=3.6=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib-resources=6.4.0=pyhd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - isort=5.13.2=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py39h8ee36c8_1
  - lcms2=2.16=ha2f27b4_0
  - lerc=4.0.0=hb486fe8_0
  - libblas=3.9.0=21_osx64_openblas
  - libbrotlicommon=1.1.0=h0dc2134_1
  - libbrotlidec=1.1.0=h0dc2134_1
  - libbrotlienc=1.1.0=h0dc2134_1
  - libcblas=3.9.0=21_osx64_openblas
  - libcxx=16.0.6=hd57cbcb_0
  - libdeflate=1.20=h49d49c5_0
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran5=13.2.0=h2873a65_3
  - libjpeg-turbo=3.0.0=h0dc2134_1
  - liblapack=3.9.0=21_osx64_openblas
  - libopenblas=0.3.26=openmp_hfef2a42_0
  - libpng=1.6.43=h92b6c6a_0
  - libsqlite=3.45.2=h92b6c6a_0
  - libtiff=4.6.0=h129831d_3
  - libwebp-base=1.3.2=h0dc2134_0
  - libxcb=1.15=hb7f2c08_0
  - libzlib=1.2.13=h8a1eda9_5
  - llvm-openmp=18.1.2=hb6ac08f_0
  - markupsafe=2.1.5=py39ha09f3b3_0
  - matplotlib=3.8.3=py39h6e9494a_0
  - matplotlib-base=3.8.3=py39h7070ae8_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4.20240210=h73e2aa4_0
  - numpy=1.26.4=py39h28c39a1_0
  - openjpeg=2.5.2=h7310d3a_0
  - openssl=3.2.1=hd75f5a5_1
  - packaging=24.0=pyhd8ed1ab_0
  - pillow=10.2.0=py39hdd30358_0
  - pint=0.23=pyhd8ed1ab_0
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=hc929b4f_1001
  - pygments=2.17.2=pyhd8ed1ab_0
  - pylint=3.1.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.18=h7a9c478_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.9=4_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - readline=8.2=h9e318b2_1
  - requests=2.31.0=pyhd8ed1ab_0
  - scipy=1.12.0=py39h0ed1e0f_2
  - setuptools=69.2.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sphinx=7.2.6=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.8=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.6=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.0.5=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.7=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_0
  - tk=8.6.13=h1abcd95_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.4=pyha770c72_0
  - tornado=6.4=py39ha09f3b3_0
  - typing-extensions=4.10.0=hd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - unicodedata2=15.1.0=py39hdc70f33_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.11=h0dc2134_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xz=5.2.6=h775f41a_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.5=h829000d_0
  - pip:
    - pyqt6==6.6.1
    - pyqt6-qt6==6.6.2
    - pyqt6-sip==13.6.0
    - qtrangeslider==0.1.5
prefix: /Users/creville/opt/anaconda3/envs/PLASMAG_mac
